자연어 처리(NLP, Natural Language Processing)

##### 텍스트의 토큰화

토큰(token) : 단어/문장/형태소 별로 작게 나누어진 하나의 단위
토큰화(tokenizeation) : 문장을 토큰으로 나누는 과정


In [2]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text = '넓은 하늘로의 비상을 꿈꾸며'

result = text_to_word_sequence(text)
print(result)

['넓은', '하늘로의', '비상을', '꿈꾸며']


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

token = Tokenizer()         # 토큰화 함수 지정
token.fit_on_texts(docs)    # 토큰화 함수에 문장 적용
print(token.word_counts)    # 단어 빈도 수를 계산한 결과 출력

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [4]:
print(token.document_count)

3


In [7]:
print(token.word_docs)

defaultdict(<class 'int'>, {'단어를': 1, '각': 1, '나누어': 1, '먼저': 1, '텍스트의': 2, '토큰화합니다': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '토큰화해야': 1, '있습니다': 1, '수': 1, '결과는': 1, '토큰화한': 1, '사용할': 1})


In [8]:
print(token.word_index)

{'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


##### 단어의 원-핫 인코딩

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [10]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [11]:
from tensorflow.keras.utils import to_categorical

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes = word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


##### 단어 임베딩

단어 임베딩(word embedding) : 원-핫 인코딩을 사용하면 토큰의 수 만큼 단어 벡터를 만들어야하기 때문에 공간적 낭비가 생김, 그 공간적 낭비를 해결하기 위한 방법(단어 유사도를 확인해 새로운 수치로 바꿔줌)

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(16, 4))

##### 텍스트를 읽고 긍정, 부정 예측하기

In [14]:
import numpy as np

# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요',
        '최고예요',
        '참 잘 만든 영화예요',
        '추천하고 싶은 영화입니다.',
        '한 번 더 보고싶네요',
        '글쎄요',
        '별로예요',
        '생각보다 지루하네요',
        '연기가 어색해요',
        '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
class_ = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [15]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [16]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, 4)      # 서로 다른 길이의 데이터를 4로 맞추기
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [18]:
word_size = len(token.word_index) + 1

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics = 'accuracy')

model.fit(padded_x, class_, 
          epochs = 20)

print(f'\nAccuracy : {model.evaluate(padded_x, class_)[1] :.4f}')

Epoch 1/20
1/1 [==============================] - 3s 3s/step - loss: 0.6996 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 20ms/step - loss: 0.6976 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6937 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 19ms/step - loss: 0.6918 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6899 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6880 - accuracy: 0.5000
Epoch 8/20
1/1 [==============================] - 0s 17ms/step - loss: 0.6861 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6842 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6823 - accuracy: 0.7000
Epoch 11/20
1/1 [==============